/*
  ___   _   _   ___   _   _ _____ ___   _   __
 / _ \ | \ | | / _ \ | \ | |_   _/ _ \ | | / /
/ /_\ \|  \| |/ /_\ \|  \| | | |/ /_\ \| |/ /
|  _  || . ` ||  _  || . ` | | ||  _  ||    \
| | | || |\  || | | || |\  | | || | | || |\  \
\_| |_/\_| \_/\_| |_/\_| \_/ \_/\_| |_/\_| \_/

Project HAIRCUT HAIRCUT.h library header
Initial file automatically generated by PROGENY on 06/21/23 02:40:35

 This file contains all header definitions used by test executables
*/

#ifndef HAIRCUT_H
#define HAIRCUT_H

#define MATPLOT

#endif //HAIRCUT_H
